name: fra-viz

services:
  backend:
    container_name: fra-viz-backend
    build: . 
    tty: true
    ports:
      - "8050:8050"
    volumes:
      - "./output:/FRA/output"
      - "./input:/FRA/input"
  frontend:
    container_name: fra-viz-frontend
    build: ./frontend
    ports:
      - 9999:3000
